version: '1'

services:
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8001:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://root:gyovS8eeXXHeHW4c3dzpJqTcCUCFtsY8@dpg-cje87s8cfp5c73bq3g8g-a.singapore-postgres.render.com/foodmanagement
    restart: unless-stopped